[project]
name = "network-agent"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "groq>=0.33.0",
    "langchain-groq>=1.0.0",
    "langgraph>=1.0.3",
    "netmiko>=4.6.0",
    "python-dotenv>=1.2.1",
]
